version: '3.8'

volumes:
  pg_data_production:
  backend_static:
  backend_media:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data_production:/var/lib/postgresql/data

  backend:
    image: harrowsdocker/kittygram_backend
    env_file: .env
    depends_on:
      - db
    volumes:
      - backend_static:/backend_static
      - backend_media:/app/media

  frontend:
    image: harrowsdocker/kittygram_frontend

  gateway:
    image: harrowsdocker/kittygram_gateway
    ports:
      - '9000:80'
    depends_on:
      - backend
      - frontend
    volumes:
      - backend_static:/static
      - backend_media:/media
